name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cURL
      run: sudo apt install libcurl4-openssl-dev
    - name: Clone Catch2
      run: git clone https://github.com/catchorg/Catch2.git
    - name: Build Catch2
      run: cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF
    - name: Install Catch2 
      run: cd Catch2 && sudo cmake --build build/ --target install
    - name: Create build directory
      run: mkdir build
    - name: Configure Cmake
      run: cd build && cmake .. 
    - name: Compilation Check
      run: cd build && make
